Module: main
Note: this file is generated by gen-makefile from Makegen

define constant $default-dylan-dir = "/usr/local";
define constant $default-dylan-user-dir = "/usr/local";

define constant $gc-libs = "-lgc -ldl -lpthread";

define constant $default-target-name = "x86-linux-gcc";
